FROM node:22-alpine AS build
WORKDIR /app
COPY package.json ./
COPY src ./src
COPY index.html vite.config.ts tsconfig.json ./
RUN npm install
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
